version: "3.7"
services:

  tests:
    build:
      context: .
    image: tech-tests
    environment: 
      BROWSER_: "${BROWSER_}"
      WDIO_ARGS_: "${WDIO_ARGS_}"
      TEST_ENV: "${TEST_ENV}"
    volumes:
      - type: bind
        source: ./reporting
        target: /framework/reporting
