version: "3.7"
services:

  tests:
    build:
      context: .
    image: tech-tests
    environment: 
      BROWSER_: "${BROWSER_}"
      SUITE_: "${SUITE_}"
    volumes:
      - type: bind
        source: ./reporting
        target: /framework/reporting
